modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/frikinjay/packtools/issues"
license = "LGPL3.0"

[[mods]]
modId = "packtools"
version = "${version}"
displayName = "Pack Tools"
authors = "frikinjay"
description = '''
Tools, utilities and features for modpacks.
'''
logoFile = "icon.png"

[[dependencies.packtools]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.packtools]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11]"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "packtools.mixins.json"

[[mixins]]
config = "packtools-neoforge.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
